### ISSUE TITLE
Error: ...non-existent package 'aws_common'

### ISSUE THREAD

**Issue by ThunderRoid** [aws-robotics/utils-common#48] opened 2019-10-31 21:37 UTC
As you can see `ros-kinetic-aws-common` is already installed, but I still get an error saying 

```
[rospack] Error: package 'lex_node' depends on non-existent package 'aws_common' 
and rosdep claims that it is not a system dependency. 
Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
```
What am I doing wrong. Any help is appreciated. 

![image](https://user-images.githubusercontent.com/3328263/67987575-07e75c00-fbeb-11e9-81c1-32888726b1b5.png)

**Comment by ryanewel** [comment] 2019-10-31 23:10
Hi @ThunderRoid,
Thanks for submitting this issue. I don't think you're doing anything wrong. I think this is caused by how we're building the `aws_common` package. Besides `rospack` not being able to find the package are you having any trouble running the node?

You didn't specify what steps you're taking to get and build your lex_pkg2, but I was able to reproduce your issue with the following steps
```
source /opt/ros/kinetic/local_setup.bash
rosdep update

mkdir -p ~/lex_ws/src && cd ~/lex_ws/src
git clone https://github.com/aws-robotics/lex-ros1.git
cd ~/lex_ws
rosdep install --from-paths src --ignore-src -r -y
colcon build
source install/local_setup.bash
rospack depends1 lex_node
```
This resulted in a similar error to yours:
```
[rospack] Error: package 'lex_node' depends on non-existent package 'lex_common' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'
```

However I was able to run the node with no problem. I've included more details below on what's causing this issue. We'll look into resolving the issue with `rospack`, but I don't think this should prevent the node from functioning.



**More Details**
The `lex_node` package depends on both `lex_common` and `aws_common`. What these two packages have in common is that they both use cmake as a build tool instead of catkin.

ROS packages installed from apt are installed into `/opt/ros/kinetic/share` and the packages are there:
```
$ ls /opt/ros/kinetic/share | grep -E '(aws)|(lex)_common'
aws_common
aws_ros1_common
lex_common
```

`rospack` is looking there for packages (can confirm with `echo $ROS_PACKAGE_PATH`), however it only identifies projects with a `package.xml` as ROS packages (see this [question](https://answers.ros.org/question/251110/rospack-cannot-find-package-made-by-cmake-even-after-sourcing/)).

```
$ ls /opt/ros/kinetic/share/aws_common
cmake
$ ls /opt/ros/kinetic/share/lex_common
cmake
$ ls /opt/ros/kinetic/share/aws_ros1_common
cmake package.xml
```

For some reason our pure cmake builds are not including the package.xml which prevents `rospack` from recognizing them but doesn't seem to impact functionality.

**Comment by ThunderRoid** [comment] 2019-11-05 00:04
Thank you so much for the reply. I got it working.

**Closed** 2019-11-11 19:08 UTC
Labels: bug

**Comment by AAlon** [comment] 2019-11-26 01:05
To add some more information: having the package.xml installed is not enough - CMake packages are simply not supported by the `rospack` and `ros2 pkg` tools and this seems like the intended behavior to me.

This is because the ROS-specific hooks that modify the environment to add the package path are not installed (see `install/lex_node/share/lex_node/hook/ros_package_path.sh`).

If you have to use those tools for CMake packages, you can of course directly edit `ROS_PACKAGE_PATH`:
```
~/rospk$ rospack depends1 lex_node
[rospack] Error: package 'lex_node' depends on non-existent package 'lex_common' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'

~/rospk$ export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/avishaya/rospk-fix/install/aws_common/share:/home/avishaya/rospk-fix/install/lex_common/share

~/rospk$ rospack depends1 lex_node
roscpp
std_msgs
lex_common
lex_common_msgs
aws_common
aws_ros1_common
```
